### ISSUE TITLE
New Model Training Problem

### ISSUE THREAD

**Issue by Terra-V** [Ekim-Yurtsever/DeepTL-Lane-Change-Classification#11]
What does each column of data in  LCTable.csv mean?

**Comment by Ekim-Yurtsever** [comment]
Columns stand for: driver id | task_id | starting_frame | end_frame | risk_score respectively. You don't need all these columns, however. And unfortunately, I cannot share the original data. You really only need risk_score if you already extracted relevant video clips from a larger video file.

In our data risk score is normalized between -1 and 1, but you can use your own scores and scale. The convert_risk_to_one_hot function will convert these values to binary risk labels. E.g, dataset.convert_risk_to_one_hot(self, risk_threshold=0.05) will take the highest 5% percent of the dataset as risky (assign 1) and the rest as safe (assign 0).
