### ISSUE TITLE
LCTable.csv structure

### ISSUE THREAD

**Issue by ynalcakan** [Ekim-Yurtsever/DeepTL-Lane-Change-Classification#3]
I'm trying to run sample scripts but to be able to run ResNet test script we need to have a "LCTable.csv" file. What should be structure of this csv file?

**Comment by Ekim-Yurtsever** [comment]
Hi. I just pushed a sample placeholder LCTable.csv to /test. Unfortunately, I cannot share the original data.

Columns stand for: driver id | task_id | starting_frame | end_frame | risk_score  respectively. 

In our data risk score is normalized between -1 and 1, but you can use your own scores and scale. The convert_risk_to_one_hot function will convert these values to binary risk labels. E.g, dataset.convert_risk_to_one_hot(self, risk_threshold=0.05) will take the highest 5% percent of the dataset as risky (assign 1) and the rest as safe (assign 0).

**Comment by ynalcakan** [comment]
Thank you for the example file and detailed info! 
I'll just create a random CSV file respect to that columns.
