### ISSUE TITLE
Please update the model weights.

### ISSUE THREAD

**Issue by tt0059** [Ekim-Yurtsever/DeepTL-Lane-Change-Classification#34]
[Only for the MaskRCNN based model] Download MaskRCNN weights* from https://www.dropbox.com/s/n81pagybkj8p5w1/mask_rcnn_coco.h5?dl=0 and move it to /test . Out of work

**Comment by Ekim-Yurtsever** [comment]
Thanks for pointing out that the link to the weights is dead. You can use the original link from matterport's implementation (it is the same weights file): https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5

I will also update the readme file accordingly. 

Thanks!
-EY
